### ISSUE TITLE
Error when using d3.v3.min.js

### ISSUE THREAD

**Issue by clovisrod** [palanikumarr/d3js-doubleside-tree#1]
Hi palanikumarr

This sample is exactly what I was looking for.

It works perfectly if I use v2:  d3.v2.js, but when I try to update to v3 ( d3.v3.js) I got errors and the links of the left side (winners) are not redered.

![image](https://user-images.githubusercontent.com/4471346/34366297-db929278-ea80-11e7-85c6-6601bff528de.png)

Any idea about how to solve it ?

Thanks

**Comment by palanikumarr** [comment]
Hi,

Sorry for the late response. I have fixed it. Please pull the latest code and Use it. :)
